### ISSUE TITLE
using batch creative interpolation meets promblem

### ISSUE THREAD

**Issue by hhd-boospi** [banodoco/Steerable-Motion#28]
Traceback (most recent call last):
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\Blender_ComfyUI\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\Steerable-Motion\SteerableMotion.py", line 425, in combined_function
    model, = ipadapter_application.apply_ipadapter(ipadapter=ipadapter, model=model, weight=1.0, image=None, weight_type="original",
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\Steerable-Motion\imports\IPAdapterPlus.py", line 501, in apply_ipadapter
    self.ipadapter = IPAdapterImport(
  File "D:\Blender_ComfyUI\ComfyUI\custom_nodes\Steerable-Motion\imports\IPAdapterPlus.py", line 241, in __init__
    self.image_proj_model.load_state_dict(ipadapter_model["image_proj"])
  File "D:\Blender_ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for ResamplerImport:
        size mismatch for proj_in.weight: copying a param with shape torch.Size([768, 1280]) from checkpoint, the shape in current model is torch.Size([768, 1024]).

How to deal with the above error report?

**Comment by peteromallet** [comment]
This is due to size of the input images being different or one of the models you're using being an SDXL one
